### ISSUE TITLE
Package.json not correctly formatted for ghost theme

### ISSUE THREAD

**Issue by Eddolan** [Bartinger/phantom#10]
I am using ghost.io and trying to upload this as a theme, but I keep getting the error:

"The theme file you have uploaded is invalid. Please ensure the contents of your zip file contain a Ghost theme as explained in the documentation."

**Comment by Bartinger** [comment]
Thanks for reporting. I was testing this a few months back and it just failed with the error: "Failed to upload theme". I'm going to have a look at this.

**Comment by Bartinger** [comment]
I assume it was a bug on their side. I just executed ```grunt compress```, uploaded the zip file and everything worked fine.
