### ISSUE TITLE
Using Open Sans with Latin-Extended 

### ISSUE THREAD

**Issue by Bartinger** [Bartinger/phantom#9]
Hi Dominic,

I just started using Ghost and I installed your theme as I think it looks really great.
I really hope I’m not bugging you, but I have one small problem with the Open Sans font. I need the latin extended chars (because I’m using  characters like ăîșțâ), and I can’t find the correct way to edit this in _fonts.scss. Can you please provide me with a hint?

Really sorry for disturbing you. Many thanks,

//ionut

**Comment by Bartinger** [comment]
Hey Ionut,
Since you're trying to edit the scss file, I assume you're using Grunt, is this correct?

All you have to do is remove the first 3 @font-face { ... } blocks, those would be Open Sans, Open Sans Bold and Roboto Regular.
Then take those font-face definitions which you find at the link below and paste them in.

http://fonts.googleapis.com/css?family=Open+Sans:700,400|Roboto&subset=latin,latin-ext

**Comment by iboldizsar** [comment]
Hey Dominic,

Thank you very much for the hint. I've done this, and those characters still do not display ok. My site is at http://ionut.boldizsar.ro - I have confirmed that the font loaded in CSS is indeed the one specified above. Am I missing something?

Many thanks,
//ionut

**Comment by iboldizsar** [comment]
Sorry. It was actually working. Ignore my post above. Thank you for your help :)

**Comment by Bartinger** [comment]
Great to hear, glad I could help
